/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_helloworld_HelloWorldJNI */

#ifndef _Included_com_example_helloworld_HelloWorldJNI
#define _Included_com_example_helloworld_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_helloworld_HelloWorldJNI
 * Method:    getPageSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_helloworld_HelloWorldJNI_getPageSize
  (JNIEnv *, jobject);

/*
 * Class:     com_example_helloworld_HelloWorldJNI
 * Method:    getCPUCores
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_helloworld_HelloWorldJNI_getCPUCores
  (JNIEnv *, jobject);

/*
 * Class:     com_example_helloworld_HelloWorldJNI
 * Method:    getCPUModel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_helloworld_HelloWorldJNI_getCPUModel
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
