/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_CPUInfo */

#ifndef _Included_com_example_jni_CPUInfo
#define _Included_com_example_jni_CPUInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_CPUInfo
 * Method:    getPageSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_jni_CPUInfo_getPageSize
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jni_CPUInfo
 * Method:    getCPUCores
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_jni_CPUInfo_getCPUCores
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jni_CPUInfo
 * Method:    getCPUModel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jni_CPUInfo_getCPUModel
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
