/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ucrypto_UCrypto */

#ifndef _Included_com_ucrypto_UCrypto
#define _Included_com_ucrypto_UCrypto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ucrypto_UCrypto
 * Method:    encrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ucrypto_UCrypto_encrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_ucrypto_UCrypto
 * Method:    decrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ucrypto_UCrypto_decrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_ucrypto_UCrypto
 * Method:    generateKey
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ucrypto_UCrypto_generateKey
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
